databases:
  - name: furniture-db
    databaseName: furniture_shop
    user: furniture_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: furniture-shop
    runtime: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: furniture-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings